services:
  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
    environment:
      - DETECT_EXTERNAL_IP=yes
    command: -c /etc/coturn/turnserver.conf