# Réseau
listening-port=3478
tls-listening-port=5349
# Écoute sur toutes les interfaces du Raspberry
listening-ip=0.0.0.0
# IP publique de ta box / connexion Internet
external-ip=82.67.57.216

# Authentification
# Utilise comme realm ton IP publique (tu pourras le changer en domaine plus tard)
realm=82.67.57.216
fingerprint
lt-cred-mech
# Identifiant/mot de passe pour ton appli WebRTC (à réutiliser dans ICE_CONFIG)
user=screenshare:ChangeThisPass!

# Relay
min-port=49152
max-port=65535
no-multicast-peers

# Logs
log-file=/var/log/coturn/turnserver.log
verbose